# This file was generated by GoReleaser. DO NOT EDIT.
class Todo < Formula
  desc "A TODO manager just for me"
  homepage "https://github.com/naoty/todo"
  version "0.4.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/naoty/todo/releases/download/0.4.1/todo_0.4.1_Darwin_x86_64.tar.gz"
    sha256 "b4444dfe77902f53f3548a7e01977c58e83844a18d9f04b97df9ade477463896"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/naoty/todo/releases/download/0.4.1/todo_0.4.1_Linux_x86_64.tar.gz"
      sha256 "577a3bfcd08baeda2dd7fb2a911f497773c6f71f67746e25faf75b5619b9e75f"
    end
  end

  def install
    bin.install "todo"
  end
end
