# This file was generated by GoReleaser. DO NOT EDIT.
class Todo < Formula
  desc       "My task manager"
  homepage   "https://github.com/naoty/todo"
  url        "https://github.com/naoty/todo/archive/refs/tags/v0.5.0.tar.gz"
  sha256     "3eb9c5b5250a27188cc3989fc14f38789fc32f22e0fb1a58e46c6ed54de0ed90"
  license    "MIT"
  depends_on "ruby"

  def install
    prefix.install "lib"
    bin.install "bin/todo"
  end
end
